pref("extensions.mailfrom.debug", false);
pref("extensions.mailfrom.default.service", "default");
pref("extensions.mailfrom.open.in", 2);
//pref("extensions.mailfrom.services", "default,aol,gmail,windowslive,yahoomail");
pref("extensions.mailfrom.services", "default,aol,gmail,yahoomail");
pref("extensions.mailfrom.service.default.enabled", true);
pref("extensions.mailfrom.service.default.name", "System Mail Client");
pref("extensions.mailfrom.service.default.url", "");
pref("extensions.mailfrom.service.aol.enabled", true);
pref("extensions.mailfrom.service.aol.name", "AOL Mail");
pref("extensions.mailfrom.service.aol.url", "http://webmail.aol.com/Mail/ComposeMessage.aspx?to=$TO&subject=$SUBJECT");
pref("extensions.mailfrom.service.gmail.enabled", true);
pref("extensions.mailfrom.service.gmail.name", "GMail");
pref("extensions.mailfrom.service.gmail.url", "https://mail.google.com/mail/?view=cm&fs=1&to=$TO&su=$SUBJECT");
// Need to work out the compose email for windows live.  Can't get around the AJAX interface so far
//pref("extensions.mailfrom.service.windowslive.enabled", true);
//pref("extensions.mailfrom.service.windowslive.name", "Windows Live");
//pref("extensions.mailfrom.service.windowslive.url", "https://mail.live.com/");
pref("extensions.mailfrom.service.yahoomail.enabled", true);
pref("extensions.mailfrom.service.yahoomail.name", "Yahoo! Mail Classic");
pref("extensions.mailfrom.service.yahoomail.url", "http://compose.mail.yahoo.com/?To=$TO&Subject=$SUBJECT");